server:
  port: ${PORT:8080}
spring:
  application:
    name: git_projects_api
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.pqajbffnmeuulffagzoo
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      max-lifetime: 60000
      connection-test-query: SELECT 1

  sql:
    init:
      mode: never

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URI}
          jwk-set-uri: ${CLERK_JWKS_URI}
