spring:
  application:
    name: git_projects_api


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URI}
          jwk-set-uri: ${CLERK_JWKS_URI}
